# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb0f86863b8cd9f494c66e8fe77c6aa8e254008af0ecc9630a88bd765e1d465ba8aad375c3442423ba6a3386bd831b0eba7b7258a1627cc2f2ff60df40d26591

test:
  secret_key_base: e485800ec5c3ec8ac257970d384ea0dd68faf216c05fc65f9e8426f7d91b7d4a8ed9598d85a612725415143436180fd28e97978e065838880f664a2121be74dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
